<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class State extends Model
{
    use \Sushi\Sushi;

    protected $rows = [
        ['brand' => 'American Express', 'bin' => 370782, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376791, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 378594, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 377664, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 377654, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 377653, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376799, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376798, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376797, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376795, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376794, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376793, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376792, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376790, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376789, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376788, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376786, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376784, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376783, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376782, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376729, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376728, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376727, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376726, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376724, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376723, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376722, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376721, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376720, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376719, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376718, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376717, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376715, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376712, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376711, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376710, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376709, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376707, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376706, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376705, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376704, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376703, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376702, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376701, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376700, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376699, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376698, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376697, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376696, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376695, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376694, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376693, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376692, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376691, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376690, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376689, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376688, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376687, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376685, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376684, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376683, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376682, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376681, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376680, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376679, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376678, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376677, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376676, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376674, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376673, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376672, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376671, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376670, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376669, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376668, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376667, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376666, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376665, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376664, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376663, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376662, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376661, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376657, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376654, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376651, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376650, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376649, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376648, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376647, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376646, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376645, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376644, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376642, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376641, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376640, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376599, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376598, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376597, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376596, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376595, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376594, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376593, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376592, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376591, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376590, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376589, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376588, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376585, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376583, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376582, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376581, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376580, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376579, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376578, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376577, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376576, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376575, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376574, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376573, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376572, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376571, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376570, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376569, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376568, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376567, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376566, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376565, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376564, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376563, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376562, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376561, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376560, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370798, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370797, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370795, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370794, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370793, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370792, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370791, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370790, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370789, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370788, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370787, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370786, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370785, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370784, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370783, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370781, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370778, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370776, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370775, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370774, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370773, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370772, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370770, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370769, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370768, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370767, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370766, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370765, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370764, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370763, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370761, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370760, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370759, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370758, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370757, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370756, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370754, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370753, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370752, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370751, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370750, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370749, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370748, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370747, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370746, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370745, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370744, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370743, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370742, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370741, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370739, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370738, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370735, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370734, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370733, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370732, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370731, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370730, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370729, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370727, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370726, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370725, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370723, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370722, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370720, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370719, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370718, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370717, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370716, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370715, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370714, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370713, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370712, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370711, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370710, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370709, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370708, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370707, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370706, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370705, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370704, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370703, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370702, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370701, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370700, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376586, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370728, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370796, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376796, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370780, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370736, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376587, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370799, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376787, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370779, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370762, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370777, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376716, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376785, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370771, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370724, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376660, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376714, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 377652, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376675, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376713, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370755, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376686, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376584, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370737, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376725, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376708, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370721, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 370740, 'country' => 'MX'],
        ['brand' => 'American Express', 'bin' => 376643, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 510586, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 511114, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 511141, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 511265, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 511747, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 511852, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 512029, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 512048, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 512280, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 514044, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 516685, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 516699, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 517586, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 517712, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 517713, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 517717, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 517721, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 517737, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 517763, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 517764, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 517767, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 517768, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 517771, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 517776, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 517777, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 517779, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 517785, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 518004, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 518174, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 518205, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 518261, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 519946, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 520021, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 520667, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 520694, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 520698, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 520699, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 521300, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 522130, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 522498, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 522618, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 523285, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 524385, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 524711, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 524782, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 524783, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 524847, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 525424, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 525678, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 525797, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 526404, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 526460, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 526498, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 526951, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 527374, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 528074, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 528480, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 528804, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 528805, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 528813, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 528814, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 528815, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 528818, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 528826, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 528828, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 528829, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 528834, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 528843, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 528851, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 528854, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 528855, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 528858, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 528861, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 528863, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 528865, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 528867, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 528873, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 528876, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 528883, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 528892, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 528893, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 528898, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 529001, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 529027, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 529028, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 529088, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 529091, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 529093, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 529575, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 530056, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 530834, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 531390, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 533987, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 534926, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 535943, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 536240, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 537033, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 537830, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 538984, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 539672, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 539946, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 540039, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 540267, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 540533, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 540845, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 540956, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 541221, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 541278, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 541286, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 541290, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 541291, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 541297, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 541298, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 541405, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 541428, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 542537, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 542834, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 542861, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 542977, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 543006, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 543183, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 543499, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 543662, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 543691, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 543722, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 543784, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 543798, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 543964, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 544053, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 544204, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 544505, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 544548, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 544551, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 544672, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 544925, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 545094, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 545290, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 545375, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 545631, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 545730, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 546080, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 546338, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 546378, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 546482, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 546483, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 546575, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 546577, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 546579, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 546580, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 546582, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 546589, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 546590, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 546688, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 546713, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 546759, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 546804, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 546829, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 546832, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 546833, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 546867, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 546868, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 546869, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 546870, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 546871, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 546872, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 547015, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 547046, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 547050, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 547066, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 547068, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 547074, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 547075, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 547077, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 547078, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 547079, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 547080, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 547086, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 547088, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 547092, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 547093, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 547095, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 547096, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 547097, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 547103, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 547106, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 547112, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 547146, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 547370, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 547380, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 547406, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 547407, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 547484, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 547488, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 547492, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 547494, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 547514, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 547736, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 547751, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 547941, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 548234, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 548236, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 549138, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 549611, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 549631, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 549639, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 549880, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 550233, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 550454, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 550569, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 550962, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 551077, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 551081, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 551253, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 551276, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 551720, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 552263, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 552488, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 553253, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 553396, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 553448, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 553467, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 553579, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 554492, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 554625, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 554628, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 554629, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 554691, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 554764, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 554900, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 554964, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 555924, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 557874, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 557905, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 557907, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 557908, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 557909, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 557910, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 557920, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 557922, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 557924, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 558306, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 558322, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 558426, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 558784, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 559209, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 540051, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 539975, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 539944, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 512809, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 512795, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 512745, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 526953, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 526949, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 526489, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 526400, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 511761, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 520660, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 520642, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 520622, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 520620, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 520606, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 520604, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 557561, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 557551, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 520499, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 522794, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 522339, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 522312, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 522174, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 551244, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 551240, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 550081, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 549920, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 537030, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 534550, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 534548, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 518899, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 518853, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 545325, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 534381, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 517775, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 517769, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 517765, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 516576, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 533609, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 543797, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 543221, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 531444, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 531298, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 531294, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 530756, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 530113, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 529081, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 528897, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 528888, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 528885, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 528881, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 528870, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 528869, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 528866, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 528862, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 528853, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 528838, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 529506, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 529023, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 529017, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 528877, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 547156, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 546588, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 546587, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 546586, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 546585, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 546584, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 546583, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 546581, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 546578, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 546576, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 546574, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 545307, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 545087, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 545039, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 544652, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 544550, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 544549, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 520213, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 517844, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 517747, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 542010, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 520610, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 523013, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 529571, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 520502, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 522289, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 512709, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 547155, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 530686, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 520318, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 539978, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 547157, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 520416, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 517795, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 518135, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 557604, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 528875, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 528890, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 551238, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 526424, 'country' => 'MX'],
        ['brand' => 'Mastercard', 'bin' => 551134, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 400486, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 402514, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 402766, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 402934, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 403703, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 403707, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 404903, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 406129, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 406130, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 407458, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 407559, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 407561, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 407848, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 408242, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 408244, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 408245, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 408343, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 408400, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 410177, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 410851, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 410852, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 413405, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 413406, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 415231, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 415269, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 416502, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 416916, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 418075, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 418094, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 418926, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 418928, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 419335, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 419663, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 419664, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 419665, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 419690, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 419691, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 421003, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 421009, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 421017, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 421811, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 421812, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 422299, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 422582, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 423173, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 423646, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 423688, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 425165, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 425766, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 425918, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 425982, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 425984, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 426188, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 426513, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 427213, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 430967, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 431479, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 431880, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 433114, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 433126, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 433465, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 434344, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 434684, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 435188, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 435741, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 435759, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 437778, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 438099, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 439120, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 439185, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 439186, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 439187, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 441310, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 441311, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 441312, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 441313, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 441505, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 441506, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 441507, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 441541, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 441542, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 441545, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 441549, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 441551, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 441567, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 442268, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 442596, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 444085, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 444449, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 445992, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 446117, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 446137, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 446138, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 446139, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 446351, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 446878, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 448790, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 449558, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 449700, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 449702, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 451299, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 451306, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 451311, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 451326, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 451331, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 451712, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 451791, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 451899, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 452412, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 452421, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 454057, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 454061, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 454069, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 454459, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 455255, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 455502, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 455503, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 455505, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 455506, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 455508, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 455510, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 455511, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 455517, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 455526, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 455527, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 455528, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 455529, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 455534, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 455535, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 455540, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 455541, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 455617, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 456300, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 456344, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 456550, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 460700, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 460766, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 461159, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 462275, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 462278, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 462974, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 463186, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 463187, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 464598, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 464599, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 465495, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 465828, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 469693, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 473701, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 474174, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 474175, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 474176, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 474646, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 476114, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 476115, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 476202, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 476203, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 476204, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 477130, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 477211, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 477212, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 477213, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 477214, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 477247, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 477260, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 477291, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 477292, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 477831, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 480862, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 483030, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 483347, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 485942, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 485943, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 486387, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 486388, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 490178, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 490642, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 491259, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 491272, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 491279, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 491280, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 491283, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 491294, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 491295, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 491327, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 491340, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 491341, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 491342, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 491343, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 491344, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 491346, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 491365, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 491366, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 491369, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 491371, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 491375, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 491376, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 491398, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 491399, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 491405, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 491406, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 491418, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 491501, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 491502, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 491512, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 491566, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 491567, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 491572, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 491573, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 491580, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 491584, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 491586, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 491591, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 491871, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 491872, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 491873, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 492487, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 493135, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 493136, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 493158, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 493161, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 493164, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 493165, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 493172, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 494133, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 494134, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 498460, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 498474, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 498588, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 498590, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 498589, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 477210, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 469849, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 481284, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 481283, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 481282, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 481281, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 481279, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 481273, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 480790, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 467508, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 451444, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 451370, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 451352, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 451298, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 450929, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 422671, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 476588, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 457476, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 432049, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 457386, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 456050, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 421364, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 446565, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 413153, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 413131, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 446118, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 446116, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 474494, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 412432, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 464597, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 464596, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 410180, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 410080, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 409852, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 409851, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 445017, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 445016, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 409365, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 418927, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 418925, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 418914, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 436401, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 404380, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 428575, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 428574, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 408341, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 454463, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 418093, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 418090, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 418080, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 418077, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 418076, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 418073, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 465829, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 427295, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 471239, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 403856, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 417968, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 417967, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 417849, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 492144, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 407304, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 426808, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 426807, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 426012, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 406447, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 491702, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 405930, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 405689, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 491271, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 403506, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 405306, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 404748, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 426514, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 402687, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 402338, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 402318, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 425981, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 442192, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 413098, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 479461, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 479438, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 416689, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 415327, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 402145, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 402029, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 451335, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 451334, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 451333, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 451332, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 451312, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 410181, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 435769, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 435768, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 450933, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 450589, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 450437, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 498462, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 433454, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 449187, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 456880, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 400820, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 400819, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 400818, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 400605, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 472309, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 448767, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 421316, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 420713, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 420199, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 494399, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 494398, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 494388, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 493708, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 493700, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 430902, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 493173, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 493166, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 493162, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 493160, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 493157, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 467473, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 455550, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 455549, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 455548, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 455546, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 455545, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 455544, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 455543, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 455542, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 455539, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 455538, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 455537, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 455536, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 455533, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 455532, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 455530, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 455520, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 455519, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 455518, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 455516, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 455514, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 455513, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 455512, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 455509, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 455507, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 455504, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 455501, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 455500, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 472303, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 433125, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 400443, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 479353, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 472323, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 401899, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 404360, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 455531, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 455515, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 451371, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 425983, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 455525, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 460068, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 429522, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 429505, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 455220, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 491284, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 491282, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 491281, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 491089, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 454747, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 454492, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 490176, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 444452, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 413475, 'country' => 'MX'],
        ['brand' => 'Visa', 'bin' => 413455, 'country' => 'MX'],
    ];
}
